import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/components/QueryClientProvider";
import { Noto_Sans_Arabic } from "next/font/google";

const inter = Noto_Sans_Arabic({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "آية",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}